language: node_js
node_js:
  - "4.1"
before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64:$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs -v
script:
  - make
  - npm test

env:
  global:
    - secure: "N4IsZPxjRZuoYgxQTLLWtWScvwtNFMrk7w71vkHZhDjzvLhx4+ms7DpkjZ5kJOe5hlx44GAMKrAKeCBwQ7nGw4HNyG168MF8cottQS+ED5V5thy/92je3BtxMoFAtHg9M1Fc1ziL06yFP8/HTua1xWmgD+lbd53CM6G+Q+VC8EzV014AZRadvYU+kCzn17SW4yw0gauhjrnq6+BwZFEv5dt7rEm4LWawp6mWFvlLICCjkGZbJbVBOlzvjdZn4zX4Mz8ZmVyxAAdUUwp3t1iSX3kd2SaODjMULoydfpaf8YD2M0wC2vA3NlynImR7lvu/eGWlyJv5CB6RH3SqrEDnAATYe3aPPqBHdCAJ/BfC2a8befmRKgbZVQ3nNgbqz80OzoTOnsNF0BF3YQrdfgSRhHS4gtfgncQ/XwciZlNFkqySjtZ78J9N+EEVaJHTVff9NRCYgaD0XllEEPH6/bjbdVFW8f7x3cqjIL6+yHycK61vEsDgfTG2bxEnxBU1urGXx/pAKgvRxHm9SQEK+8eRLgqgw7iSrhM3sNZowq9iioz5e1JXHIITqiDV4wJj0eNpQlfzoxMtAIedRr0aTTrES6ioz+Km1Ap4Wg49RnO4BM6WK9WDKBxgsUjlUMwpa21mTuP6BUgdgKa/6wnK2B+PI+0+wAyEjvfh2HXxUML5Onw="

deploy:
  provider: script
  script: script/travis_deploy.sh
